version: 1.0
project:
  name: Tuza-assets
  type: php
  php_version: "8.3"

runtime:
  php:
    version: "8.3"
    enabled: true
  cron-jobs: []

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan migrate --force
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    pre-deployment-remote-commands:
      - php artisan down
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan migrate --force
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up
