version: 1.0

project:
  name: Tuza-assets
  type: php
  php_version: "8.3"

runtime:
  php:
    version: "8.3"
    enabled: true

deploy:
  bootstrap:
    excludes:
      - tests
      - node_modules
      - output.log
    post-deployment-remote-commands:
      - php artisan migrate --force
      - php artisan storage:link
      - php artisan optimize

  recurring:
    excludes:
      - tests
      - node_modules
      - output.log
      - storage
    pre-deployment-remote-commands:
      - php artisan down
    post-deployment-remote-commands:
      - php artisan migrate --force
      - php artisan storage:link
      - php artisan optimize
      - php artisan up
